name: Node.js CI PR Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Make envs
      run: |
        echo "CLOUDFLARE_AUTH_EMAIL=${{secrets.X_AUTH_EMAIL}}" >> .env
        echo "CLOUDFLARE_AUTH_KEY=${{secrets.X_AUTH_KEY}}" >> .env
        echo "CLOUDFLARE_SITE_NAME=${{secrets.FQDN}}" >> .env
        echo "EXAMPLE_GREETING=Phantom" >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm run lint
    - run: npm run test
    - run: cat "dist/bundled-worker.js"
